### ISSUE TITLE
Make the bot better and centered around learning / building random sentences instead of being a generic IRC bot

### ISSUE THREAD

**Issue by garyttierney** [stevesoltys/aibot#1]
I pushed something I wrote up in Ruby, uses a SQLite database. Have some plans to make it smarter than the typical chat bot https://gitlab.com/gary.tierney/rubyaibot/tree/master

**Comment by stevesoltys** [comment]
Looks good. I think moving this project over to Ruby would make it much cleaner. SQLite is also a good improvement.

**Comment by stevesoltys** [comment]
My latest commit fixes this issue.
